UNTERSTUFE_REGEX = r"((([5-9]|10|11)[A-Z]{1})|(([5-9]|10|11)[a-z]+[1-9])|(([5-9]|10|11)[a-z]+))"
OBERSTUFE_REGEX = r"([1234][a-z]+[123456789])"
TEACHER_REGEX = r"([A-ZÄÜÖ]{2,4})"

UNTERSTUFE_EXAM_TEACHER_REGEX = f"(.+\sin\s.+\s\({TEACHER_REGEX}\))"
UNTERSTUFE_EXAM_CLASS_TEACHER_REGEX = f"(.+\sin\s.+\s\({UNTERSTUFE_REGEX}\)\s\({TEACHER_REGEX}\))"
OBERSTUFE_EXAM_REGEX = f"(.+\sin\s{OBERSTUFE_REGEX}\s\({OBERSTUFE_REGEX} - {TEACHER_REGEX}\))"
