"""autogenerate_tables

Revision ID: e25ad2351c2d
Revises: 
Create Date: 2023-08-27 12:46:57.458513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25ad2351c2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('isTeacher', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('isOberstufe', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('courses', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['teacher'], ['teachers.abbreviation'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('portal_email', sa.String(), nullable=False),
    sa.Column('portal_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('substitute_teacher', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('replaced_teacher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_teacher'], ['teachers.abbreviation'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_teacher'], ['teachers.abbreviation'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substitutions')
    op.drop_table('student_absences')
    op.drop_table('exams')
    op.drop_table('users')
    op.drop_table('teachers')
    # ### end Alembic commands ###
